[database]
url = ""

[pipeman]
holding_dir = ""
i18n_paths_file = ""

[pipeman.plugins]
#first = ["plugin1", "plugin2"]
#last = ["plugin3", "plugin4"]
#skip = ["plugin5"]

[pipeman.dataset_api.defaults]
# activation_workflow = "direct_activation"
# publication_workflow = "direct_publish"
# organization_shortname = "my_org"
# security_level = "unclassified"

[pipeman.security]
#random_characters = ""
#random_password_length = 10
#hash_algorithm = "sha256"
#hash_rounds = 50000 # cannot set below 100,000
#salt_length = 32
#max_length = 1024
pepper = ""
past_peppers = [""]
#password_min_length = 0
allowed_hosts = [
    "localhost:5000"
]
require_https = false
check_get_referers = false
check_refs_default = true
check_https_default = true

#[pipeman.security.password_complexity_classes]
#lowercase = [a-z]
#uppercase = [A-Z]
#number = [0-9]
# etc...

[autoinject]
#"pipeman.auth.auth.AuthenticationManager" = "pipeman.builtins.auth_db.DatabaseEntityAuthenticationManager"
#"pipeman.i18n.i18n.TranslationManager" = "pipeman.builtins.i18n_yaml.translator.YamlTranslationManager"
#"pipeman.i18n.i18n.LanguageDetector" = "pipeman.builtins.basic_lang_detect.detector.BasicRequestLanguageDetector"

[pipeman.i18n_yaml]
#dictionary_path = ""


[pipeman.authentication]
#login_route = "home"
#logout_route = "logged_out"
#unauthorized_route = "home"
#login_required = "auth.login"

[flask]
#SECRET_KEY = ""
